apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-tracer-frontend-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: prod
    application: product-tracer-frontend
spec:
  project: default
  source:
    repoURL: https://github.com/Giabaoday/DevSecOps_Project
    targetRevision: main
    path: helm/frontend
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: "prod-latest"
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      managedFieldsManagers:
        - kube-controller-manager